name: triliumnext
services:
  trilium:
    command: []
    container_name: triliumnext
    deploy:
      resources:
        reservations:
          memory: "256M"
    image: triliumnext/notes:latest
    labels:
      icon: https://icon.casaos.io/main/all/trilium.png
    ports:
      - target: 8080
        published: "8088"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/triliumnext
        target: /home/node/trilium-data
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  author: zadam
  category: Notes
  description:
    en_us: TriliumNext Notes is actively developed fork of Trilium Notes, a hierarchical note-taking application with a focus on building large personal knowledge bases.
    zh_cn: TriliumNext Notes 是 Trilium Notes 的活跃开发分支，一个具有层次结构的笔记应用程序，专注于构建庞大的个人知识库。
  developer: triliumnext
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Trilium/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Trilium/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Trilium/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Trilium/screenshot-3.png
  index: /
  port_map: "8088"
  scheme: http
  store_app_id: triliumnext
  title:
    en_us: TriliumNext
    zh_cn: TriliumNext
